name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit:
    runs-on: self-hosted
    container:
      image: commitlint/commitlint@sha256:48a8db5da28cfb90c5a74e3ecf212ef0f70b68842f23cb48645555bfe31660f0
      options: --entrypoint /bin/sh

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Lint commit
        env:
          EVENT_NAME: ${{ forgejo.event_name }}
          PR_TITLE: ${{ forgejo.event.pull_request.title }}
          COMMIT_MESSAGE: ${{ forgejo.event.head_commit.message }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            echo "$PR_TITLE" | commitlint
          else
            echo "$COMMIT_MESSAGE" | commitlint
          fi
