name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit:
    runs-on: self-hosted
    container:
      image: commitlint/commitlint@sha256:dbdaa20bfa1cac85b0e025664310ec38dbd9804208f6d5b45dacdccbf5e4c48a
      options: --entrypoint /bin/sh

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 1

      - name: Lint commit
        env:
          EVENT_NAME: ${{ forgejo.event_name }}
          PR_TITLE: ${{ forgejo.event.pull_request.title }}
          COMMIT_MESSAGE: ${{ forgejo.event.head_commit.message }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            echo "$PR_TITLE" | commitlint
          else
            echo "$COMMIT_MESSAGE" | commitlint
          fi
