name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-commit:
    runs-on: self-hosted
    container:
      image: commitlint/commitlint@sha256:ce1a12f3ddfac34ca6467012d9bab59049aa6fd1d3f70c095d2dd6737c34b028
      options: --entrypoint /bin/sh

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1

      - name: Lint commit
        env:
          EVENT_NAME: ${{ forgejo.event_name }}
          PR_TITLE: ${{ forgejo.event.pull_request.title }}
          COMMIT_MESSAGE: ${{ forgejo.event.head_commit.message }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            echo "$PR_TITLE" | commitlint
          else
            echo "$COMMIT_MESSAGE" | commitlint
          fi
