name: Cleanup PR Registry

on:
  pull_request:
    types: [closed]

jobs:
  delete-tag:
    runs-on: self-hosted
    container:
      image: alpine/curl:latest@sha256:b5a8273cf8dd8be679ffed398269dff58cc6049647f9d62e551ff358e6c09113
    steps:
      - name: Delete PR Tag from Registry
        run: |
          # image tag name
          TAG_NAME="pr-${{ forgejo.event.pull_request.number }}"

          echo "Deleting tag $TAG_NAME from package ${{ forgejo.event.repository.name }} from owner ${{ forgejo.repository_owner }} in registry ${{ vars.REGISTRY }}"

          HTTP_STATUS=$(curl --no-progress-meter -o /dev/null -w "%{http_code}" -X DELETE \
            -H "Authorization: token ${{ secrets.REGISTRY_PASS }}" \
            "https://${{ vars.REGISTRY }}/api/v1/packages/${{ forgejo.repository_owner }}/container/${{ forgejo.event.repository.name }}/$TAG_NAME")

          case "$HTTP_STATUS" in
            204)
              echo "Deleted PR tag: $TAG_NAME"
              ;;
            404)
              echo "PR tag not found: $TAG_NAME"
              ;;
            *)
              echo "Failed to delete PR tag $TAG_NAME: HTTP $HTTP_STATUS"
              exit 1
              ;;
          esac
