name: Renovate Bot
enable-email-notifications: true

on:
  schedule:
    # 21:30 UTC = 03:00 IST
    - cron: "30 22 * * *"
  # Allow manual triggers from the Codeberg Actions UI
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate Bump PRs
    runs-on: self-hosted-dedicated

    container:
      image: ghcr.io/renovatebot/renovate@sha256:4c84638a2b70b2fe2c3bbf87d25e6f8aba40d83f8ca2b7c0bd3d0f1a4591ef7b

    steps:
      - name: Run Renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://codeberg.org/api/v1

          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GH_TOKEN }}

          RENOVATE_AUTODISCOVER: "false"

          RENOVATE_REPOSITORIES: ${{ forgejo.repository }}

          LOG_LEVEL: info
        run: renovate
